basePath: /
definitions:
  handler.response:
    properties:
      message:
        type: string
      result: {}
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: zduisekov@gmail.com
    name: API Support
  title: http-3rdparty-task-service API
paths:
  /api/v1/task:
    get:
      consumes:
      - '*/*'
      description: назначение задачи.
      produces:
      - application/json
      responses:
        "200":
          description: успешный ответ
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: ошибка запроса
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: ошибка сервера
          schema:
            $ref: '#/definitions/handler.response'
      summary: Назначить задачу
      tags:
      - task
schemes:
- http
swagger: "2.0"
