basePath: /
definitions:
  handler.AssignTaskReq:
    properties:
      body:
        example: some body
        type: string
      headers:
        additionalProperties:
          type: string
        example:
          '''Authentication''''': ' ''Basic bG9naW46cGFzc3dvcmQ='''
        type: object
      method:
        example: GET
        type: string
      url:
        example: http://google.com
        type: string
    type: object
  handler.response:
    properties:
      message:
        type: string
      result: {}
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: zduisekov@gmail.com
    name: API Support
  title: http-3rdparty-task-service API
paths:
  /api/v1/task:
    post:
      consumes:
      - application/json
      description: назначение задачи.
      parameters:
      - description: тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.AssignTaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: успешный ответ
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: ошибка запроса
          schema:
            $ref: '#/definitions/handler.response'
        "406":
          description: ошибка валидации
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: ошибка сервера
          schema:
            $ref: '#/definitions/handler.response'
      security:
      - BasicAuth: []
      summary: Назначить задачу
      tags:
      - task
  /api/v1/task/{id}:
    get:
      consumes:
      - '*/*'
      description: проверка статуса задачи.
      parameters:
      - description: comment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: успешный ответ
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: ошибка запроса
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: ошибка сервера
          schema:
            $ref: '#/definitions/handler.response'
      security:
      - BasicAuth: []
      summary: Проверить статус задачи
      tags:
      - task
schemes:
- http
swagger: "2.0"
