basePath: /
host: localhost:3000
info:
  contact:
    email: zduisekov@gmail.com
    name: API Support
  title: http-3rdparty-task-service API
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show an account
      tags:
      - accounts
  /api/v1/task:
    get:
      consumes:
      - '*/*'
      description: назначение задачи.
      produces:
      - application/json
      responses:
        "200":
          description: успешный ответ
          schema:
            type: string
        "400":
          description: ошибка запроса
          schema:
            type: string
        "500":
          description: ошибка сервера
          schema:
            type: string
      summary: Назначить задачу
      tags:
      - task
schemes:
- http
swagger: "2.0"
